import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Switch, Alert, StatusBar, TextInput } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient'; import { ArrowLeft, Shield, Lock } from 'lucide-react-native';
import { useTheme } from '../../context/ThemeContext'; import { auth } from '../../services/api';
export default function AccountSecurityScreen({ navigation }) { const { theme, isDark }=useTheme(); const [status,setStatus]=useState(null); const [busy,setBusy]=useState(false); const [code,setCode]=useState('');
 useEffect(()=>{auth.mfaStatus().then(setStatus).catch(()=>setStatus(null));},[]); const enabled=!!status?.enabled;
 const toggle=async (value)=>{setBusy(true); try { if(value){ await auth.mfaEnroll('email'); Alert.alert('Verification sent','Enter the code sent to your email.'); } else { await auth.mfaVerify({ action:'disable', code }); } const next=await auth.mfaStatus(); setStatus(next); } catch(e){Alert.alert('Could not update 2FA',e.message||'Please try again.');} finally{setBusy(false);} };
 return <View style={[styles.root,{backgroundColor:theme.bg}]}><StatusBar barStyle={theme.statusBar} backgroundColor={theme.bg}/><LinearGradient colors={theme.gradientBg} style={StyleSheet.absoluteFillObject}/><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()} style={styles.back}><ArrowLeft size={20} color={theme.textPrimary}/></TouchableOpacity><Text style={[styles.title,{color:theme.textPrimary}]}>Account Security</Text><View style={{width:40}}/></View><ScrollView contentContainerStyle={styles.content}><View style={styles.hero}><Shield size={38} color={theme.primary}/><Text style={[styles.heading,{color:theme.textPrimary}]}>Protect your account</Text><Text style={[styles.copy,{color:theme.textSecondary}]}>Your gaming assets are protected by accepted security standards.</Text></View><View style={[styles.card,{backgroundColor:theme.cardBg,borderColor:theme.cardBorderSubtle}]}><Lock size={24} color={theme.primary}/><View style={{flex:1,marginLeft:14}}><Text style={[styles.cardTitle,{color:theme.textPrimary}]}>Two-factor authentication</Text><Text style={[styles.copy,{color:theme.textSecondary}]}>Use an email verification code when signing in.</Text></View><Switch value={enabled} disabled={busy} onValueChange={toggle} trackColor={{false:'#334155',true:'#FF5500'}}/></View>{!enabled&&<TextInput value={code} onChangeText={setCode} placeholder="Verification code" placeholderTextColor={theme.textMuted} keyboardType="number-pad" style={[styles.input,{color:theme.textPrimary,borderColor:theme.inputBorder,backgroundColor:theme.inputBg}]}/>}</ScrollView></View> }
const styles=StyleSheet.create({root:{flex:1},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:20,paddingTop:60},back:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center'},title:{fontSize:22,fontWeight:'800'},content:{padding:20},hero:{alignItems:'center',paddingVertical:25},heading:{fontSize:26,fontWeight:'900',marginTop:12},copy:{fontSize:14,lineHeight:20,marginTop:8},card:{flexDirection:'row',alignItems:'center',padding:18,borderWidth:1,borderRadius:18,marginTop:16},cardTitle:{fontSize:16,fontWeight:'800'},input:{marginTop:16,borderWidth:1,borderRadius:12,padding:14}});

